In [6]:
#Importing libraries

import pandas as pd
import json
import os

In [7]:
# !pip install pandas

In [8]:
# Loading the json data 
root_data_dir='/Users/HVMS/Desktop/GitHub/CineAI/data'

In [9]:
for sub_dir in sorted(os.listdir(root_data_dir)):
    print(sub_dir)  # Print each subdirectory in order

2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023

In [10]:
for sub_dir in sorted(os.listdir(root_data_dir+ '/2000/')):
    print(sub_dir)

batch_001.json
batch_002.json
batch_003.json
batch_004.json
batch_005.json
batch_006.json
batch_007.json
batch_008.json

In [11]:
test_batch_1_2000 = root_data_dir+ '/2000/batch_001.json'
with open(test_batch_1_2000, 'r') as file_1:
    data_1 = json.load(file_1)

In [12]:
len(data_1)

1000

In [13]:
#To get movie ID
for movie_id in data_1:
    for keys,values in movie_id.items():
        print(keys)

98
8871
7443
9532
77
8358
22705
10867
4247
11688
10567
2123
2024
1359
1443
4234
3134
8843
5833
10501
1443
8358
10637
1900
10577
1636
9741
16366
107
2085
5994
5833
9600
2069
9679
11978
843
3536
20677
9383
9679
11978
9383
8584
1907
146
10559
10393
12107
3176
2085
1636
1493
10647
2655
59709
11518
10035
15999
19576
20677
10577
3536
16234
243
10481
10876
19457
71
10991
2155
9600
10783
36968
5551
2440
15653
49948
8452
641
2069
2067
5491
16
11075
9456
1597
134
889
4244
10571
55892
20770
8859
10461
12609
2332
10687
11973
21614
10571
5551
889
479
7290
20455
18079
8653
18041
14626
8452
49948
19419
1588
10641
105904
10471
24102
10873
193457
1588
30628
4958
101514
2787
31347
41245
447399
62182
392
10569
11366
12211
9871
105904
711
327
18011
10473
10862
8653
193457
16340
16187
117087
10385
8870
12480
10560
10597
18041
10429
11983
14805
10472
48246
13785
37588
60670
55888
10873
24102
1163
14181
919
10642
44321
44853
28031
11599
10562
21355
24100
41275
12650
24664
24476
10180
10480
30970
18079
19348
4226
6521
318
40466
27092
14736
10763
1837
9674
5001
2621
39468
20455
37302
2360
49979
29458
16225
31352
17908
18074
11119
112
258919
10688
30944
21531
16888
159666
11477
10383
11478
29572
1619
27181
29512
29015
12597
7290
19419
12619
27027
15489
40096
10416
9011
1242945
15319
14295
16990
742
37691
1698
336970
36301
17711
9791
4967
32834
1831
22597
16110
38047
75571
13930
10394
44203
92208
20993
13966
3178
89473
200995
19150
87867
9519
35650
10697
10394
258919
11119
12480
15489
52684
10391
30940
1609
18168
39468
8870
190794
18074
51333
21991
34729
65592
37722
2805
18168
51333
18292
196737
20637
22617
193932
244839
55101
131940
5257
34729
20697
98299
52654
197725
12509
26245
32250
36234
37722
39242
4973
50008
27711
27099
204839
44412
49291
48944
52684
50531
3716
7093
190794
44388
29270
14195
44379
23990
2805
32536
27320
14629
42332
60703
28346
43586
576359
87107
43555
10391
20067
64269
53105
415488
46462
19214
33347
25128
71887
36380
49135
27745
34899
27444
10305
12806
60587
21056
299024
65592
248058
92620
25014
23618
44490
71235
26450
45438
25014
23618
89473
248058
45438
26450
44490
348864
51531
61064
87867
60703
71235
207693
41656
31774
5247
44933
288116
2707
51107
32309
89297
207937
10205
19349
72753
41282
12724
21370
30940
106230
45418
44488
62127
350893
48328
41165
10499
157800
77519
45488
34027
261111
72356
31875
16275
45602
42877
9375
45511
85411
47595
166813
685908
46958
44756
21174
36047
444008
22426
35066
45861
51767
31053
33504
49514
47943
28745
25636
61064
291334
77921
45573
55296
221506
2089
110977
50380
15940
81277
125173
118727
29866
35064
77434
100607
6147
40249
26665
32567
81207
31443
267409
32067
44947
60074
23531
37998
322686
38132
3173
193526
39927
13898
43079
214680
47244
39056
174412
12255
18394
46406
10613
13899
9883
10558
60579
36273
10989
291312
39907
34856
196280
88494
120128
389437
49709
20152
19505
36246
195791
45043
17208
39880
50477
230562
27859
30440
38274
31610
348862
24470
187107
111244
25212
25520
62004
14273
34037
31776
55551
47191
9301
45389
51179
106813
218188
16404
72392
610133
45463
188032
407312
37047
45124
56666
48217
36753
15869
604999
54380
29937
75531
264117
9565
11925
54690
218183
52409
34704
19600
186315
57450
20883
33994
114162
64526
10469
17806
291726
203071
43592
36923
60119
25293
45548
77787
49453
195655
329269
27734
127849
1051942
75049
344225
61578
58195
21117
45490
38294
85214
108811
107277
52622
61849
28943
55921
428006
21842
291721
26436
153913
76177
51422
34299
75697
77576
167880
20438
106199
95136
276846
52790
90881
431229
213914
38135
166231
72261
51531
348864
36817
64266
61641
109051
52051
22470
30148
78452
52852
20276
45952
47724
77332
154299
496537
36044
103152
47302
207693
27540
72998
71115
15090
18778
89345
44387
302466
38503
211277
44047
25651
200419
433111
887789
40562
29136
69426
27742
58976
45905
5643
9892
271917
3218
43674
68572
28349
354674
122163
51861
68820
60452
171120
64357
874667
446774
62333
81760
89068
54986
124134
326924
273106
9995
49035
46119
37716
45055
41571
30809
74578
28988
637105
117262
44131
23751
273510
48123
29946
45123
186047
206163
5245
39498
206053
86008
10415
214246
72270
612521
201447
41425
71618
434965
76265
106234
75217
31920
66796
49785
31001
116790
416715
443716
205608
86781
217428
256104
115717
78962
113213
3152
140511
330698
126733
209084
100801
56419
203831
52833
66464
24104
24955
55026
49511
41644
357682
58062
289673
80959
281014
85265
265760
351196
450187
452440
15993
287807
175240
27736
395337
20445
41381
88660
99754
28127
62729
447511
60065
76819
188154
248904
44574
200919
256050
70773
30947
385502
50477
38274
51824
164123
191378
267569
281308
2394
115469
41738
62004
31610
477164
33901
49453
106813
25212
37047
352815
45389
348762
254981
447719
171106
72087
16874
276456
27336
64114
107975
99011
155666
110999
181056
128862
11303
178582
21620
598278
384093
31006
277073
34794
158431
55143
20585
71884
167087
71550
116011
343321
30780
408129
414353
21488
290537
32249
118170
423976
880144
254981
201447
11925
56419
302466
330443
302508
390948
259730
16673
218183
67252
160832
41644
264806
356083
252615
245934
48868
73455
67252
376730
922327
165573
37730
364475
235423
88007
15496
23655
73642
29941
96716
33901
453230
31321
321023
1021910
351208
156682
107312
55302
63607
107942
286922
693072
79704
45203
49947
81219
69659
123187
82348
40930
1024825
213867
74824
271667
23430
44845
267569
103688
261459
340017
284183
844452
641425
45302
72244
10492
166283
75953
60585
62124
155588
75864
109926
75778
279700
364264
191378
41738
1185915
160832
88910
221501
1184877
57704
51864
169801
82103
102242
42195
24908
390959
252356
701212
38390
38987
18153
477164
318602
360411
31778
203820
45474
194529
77620
83581
434134
345864
48868
366978
66159
214014
261561
64310
34056
315978
116688
201724
1107965
166899
112977
77908
73838
448324
39793
199747
83870
40010
1009586
104613
217175
182511
221841
229428
88634
265307
106490
77332
47724
25651
66796
45952
45302
78620
132393
208910
10561
31920
89345
152163
267512
44387
15090
426506
40390
2090
471732
352815
79080
196139
30717
114620
273410
427108
239547
209133
231193
89823
339308
103635
1067248
436039
49773
23537
27775
31140
161219

In [14]:
# To get movie individual keys columns such as(endpoints) - expecting 15 endpoints

first_movie = data_1[0]
movie_id = list(first_movie.keys())[0]
endpoints = first_movie[movie_id].keys()

print(f"Endpoints for movie ID {movie_id}:")
for endpoint in endpoints:
    print(f"- {endpoint}")

Endpoints for movie ID 98:
- details
- credits
- recommendations
- watch_providers

In [15]:
# Getting keys from 'details' endpoint for first movie
first_movie = data_1[0]  # Get first movie
movie_id = list(first_movie.keys())[0]  # Get movie ID
details_keys = first_movie[movie_id]['details'].keys()  # Get details keys

print(f"\nKeys in 'details' for movie {movie_id}:")
for key in sorted(details_keys):
    print(f"- {key}")

Keys in 'details' for movie 98:
- genres
- id
- original_language
- overview
- popularity
- release_date
- runtime
- title

In [16]:
# Getting the first movie and its ID
movie = data_1[0]
movie_id = list(movie.keys())[0]
movie_data = movie[movie_id]

# Print all endpoint keys
print(f"\nAll endpoint keys for movie ID {movie_id}:")
for endpoint in sorted(movie_data.keys()):
    print(f"\n{endpoint.upper()} keys:")
    try:
        keys = movie_data[endpoint].keys()
        for key in sorted(keys):
            print(f"- {key}")
    except AttributeError:
        print("(No nested keys)")

All endpoint keys for movie ID 98:

CREDITS keys:
- cast
- crew

DETAILS keys:
- genres
- id
- original_language
- overview
- popularity
- release_date
- runtime
- title

RECOMMENDATIONS keys:
- results

WATCH_PROVIDERS keys:
- results

In [17]:
movie = data_1[0]
movie_id = list(movie.keys())[0]
movie_data = movie[movie_id]

# Initializing counter
total_keys = 0

# To Count and print keys for each endpoint
print(f"\nKey counts for movie ID {movie_id}:")
for endpoint in sorted(movie_data.keys()):
    try:
        keys = movie_data[endpoint].keys()
        num_keys = len(keys)
        total_keys += num_keys
        print(f"{endpoint}: {num_keys} keys")
    except AttributeError:
        print(f"{endpoint}: No nested keys")

print(f"\nTotal number of keys across all endpoints: {total_keys}")

Key counts for movie ID 98:
credits: 2 keys
details: 8 keys
recommendations: 1 keys
watch_providers: 1 keys

Total number of keys across all endpoints: 12

In [18]:
movie = data_1[0]
movie_id = list(movie.keys())[0]
movie_data = movie[movie_id]

# Assuming the details are nested within another dictionary, for example under 'details'
details = movie_data.get('details', {})

# Extracting the required details from the nested dictionary
title = details.get('title', 'N/A')
runtime = details.get('runtime', 'N/A')
release_date = details.get('release_date', 'N/A')
genres = details.get('genres', 'N/A')
overview = details.get('overview', 'N/A')

# Printing the extracted details
print(f"Title: {title}")
print(f"Runtime: {runtime} minutes")
print(f"Release Date: {release_date}")
print(f"Genres: {genres}")
print(f"Overview: {overview}")

Title: Gladiator
Runtime: 155 minutes
Release Date: 2000-05-04
Genres: [{'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}, {'id': 12, 'name': 'Adventure'}]
Overview: In the year 180, the death of Emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army's most capable and trusted generals, as well as a key advisor to the emperor. As Marcus' devious son Commodus ascends to the throne, Maximus is sentenced to execution. He escapes but is captured by slave traders. Renamed "Spaniard" and forced to become a gladiator, Maximus must battle to the death against other men for the amusement of paying audiences.

In [19]:
# # Extracting movie details
# movie_id = list(data_1[0].keys())[0]
# movie_data = data_1[0][movie_id]

# details = movie_data.get('details', {})
# movie_dict = {
#     'Title': details.get('title', 'N/A'),
#     'Runtime': details.get('runtime', 'N/A'),
#     'Release Date': details.get('release_date', 'N/A'),
#     'Genres': ', '.join([genre['name'] for genre in details.get('genres', [])]),
#     'Overview': details.get('overview', 'N/A')
# }

# # # Creating DataFrame
# # df = pd.DataFrame([movie_dict])  # Convert dictionary to DataFrame
# # print(df)

In [20]:
# Remove .DS_Store file if it exists
ds_store_path = os.path.join(root_data_dir, '.DS_Store')
if os.path.exists(ds_store_path):
    os.remove(ds_store_path)
    print('.DS_Store file removed')
else:
    print('.DS_Store file not found')

.DS_Store file not found

### All the movies data into movie dataframe

In [21]:
def data_pipeline(root_dir):
    all_movie_details = []
    for year_dir in os.listdir(root_dir):
        year_path = os.path.join(root_dir, year_dir)
        if os.path.isdir(year_path):
            for json_file in sorted(os.listdir(year_path)):
                file_path = os.path.join(year_path, json_file)
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        data = json.load(f)

                    for movie in data:
                        movie_id = list(movie.keys())[0]
                        movie_data = movie[movie_id]
                        details = movie_data.get('details', {})

                        movie_details = {
                            'movie_id': movie_id,
                            'year': year_dir, # Add year
                            'Title': details.get('title', 'N/A'),
                            'Runtime': details.get('runtime', 'N/A'),
                            'Release Date': details.get('release_date', 'N/A'),
                            'Genres': ', '.join([genre['name'] for genre in details.get('genres', [])]),
                            'Overview': details.get('overview', 'N/A')
                        }
                        all_movie_details.append(movie_details)
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON in {file_path}: {e}")
                except Exception as e: #catch all other exceptions
                  print(f"An unexpected error occurred: {e}")
    return pd.DataFrame(all_movie_details)

In [22]:
# Example usage
movie_df = data_pipeline(root_data_dir)

In [23]:
movie_df.tail(5)

,movie_id,year,Title,Runtime,Release Date,Genres,Overview
234847,533005,2004,Whispering Pines 3,8,2004-01-01,,"In her celebrated video art serial, Whispering..."
234848,531637,2004,Secrets of Pearl Harbor,44,2004-12-10,,Dennis Haysbert dives 160 feet beneath the wav...
234849,532486,2004,Los hijos del último jardín,0,2004-01-01,Thriller,
234850,530897,2004,Comme un poisson dans l'eau,18,2004-01-21,,"Daniel is in search of happiness, of human rel..."
234851,531628,2004,Quest for Columbus: In Search of the Santa Maria,44,2004-03-01,,Quest for Columbus: In Search of the Santa Mar...

In [24]:
movie_df.columns

Index(['movie_id', 'year', 'Title', 'Runtime', 'Release Date', 'Genres',
       'Overview'],
      dtype='object')

In [25]:
movie_df.shape

(234852, 7)

In [26]:
# df copy
movie_df_copy = movie_df.copy()

In [41]:
#copy of movie_df

movie_df_copy.shape

(234852, 7)

# Performing EDA Aanalysis

In [42]:
# Check for missing values in each column
movie_df_copy.isnull().sum()

movie_id        0
year            0
Title           0
Runtime         0
Release Date    0
Genres          0
Overview        0
dtype: int64

In [43]:
# Drop rows with missing values
movie_df_copy = movie_df.dropna()

In [44]:
movie_df_copy.columns

Index(['movie_id', 'year', 'Title', 'Runtime', 'Release Date', 'Genres',
       'Overview'],
      dtype='object')

In [45]:
# Basic statistics
print("Dataset Shape:", movie_df_copy.shape)
print("\nBasic Statistics:")
print(movie_df_copy.describe())

Dataset Shape: (234852, 7)

Basic Statistics:
       movie_id    year   Title  Runtime Release Date       Genres Overview
count    234852  234852  234852   234852       234852       234852   234852
unique   230587      24  207028      462         8768         7645   206276
top     1193094    2013    Home        0   2003-01-01  Documentary
freq          3   10000      46    30538         2288        34654    23240

In [46]:
# Data quality checks
quality_check = {
    'nulls': movie_df_copy.isnull().sum(),
    'zeros': (movie_df_copy[['movie_id', 'year', 'Runtime']] == 0).sum(),
    'empty_strings': (movie_df_copy[['Title', 'Genres', 'Overview']] == '').sum(),
    'duplicate_rows': movie_df_copy.duplicated().sum(),
    'invalid_dates': pd.to_datetime(movie_df_copy['Release Date'], errors='coerce').isnull().sum()  # Count invalid dates
}

In [47]:
print("Data Quality Report:")
for check, result in quality_check.items():
    print(f"\n{check.upper()}:")
    print(result)

Data Quality Report:

NULLS:
movie_id        0
year            0
Title           0
Runtime         0
Release Date    0
Genres          0
Overview        0
dtype: int64

ZEROS:
movie_id        0
year            0
Runtime     30538
dtype: int64

EMPTY_STRINGS:
Title           0
Genres      31251
Overview    23240
dtype: int64

DUPLICATE_ROWS:
4265

INVALID_DATES:
7

In [34]:
# Visualizing key distributions
import matplotlib.pyplot as plt

# !pip install seaborn
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
# Set default style without using style.use
plt.figure(figsize=(15, 10))

# Create subplots
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 12))

In [ ]:
# Step 1: Clean the Runtime column
movie_df['Runtime'] = pd.to_numeric(movie_df['Runtime'], errors='coerce')

In [ ]:

# 1. Runtime Distribution
sns.histplot(data=movie_df, x='Runtime', bins=30, ax=ax1)
ax1.set_title('Distribution of Movie Runtimes')
ax1.set_xlabel('Runtime (minutes)')

In [ ]:
# 2. Movies by Year
sns.histplot(data=movie_df, x='year', bins=30, ax=ax2)
ax2.set_title('Movies by Release Year')

In [ ]:
# 3. Top 10 Genres
genre_counts = movie_df['Genres'].value_counts().head(10)
genre_counts.plot(kind='bar', ax=ax3)
ax3.set_title('Top 10 Movie Genres')
ax3.tick_params(axis='x', rotation=45)

In [ ]:
# 4. Movies by Month (handling N/A values)
# Convert Release Date to datetime, replacing invalid values with NaT
movie_df['Release Date'] = pd.to_datetime(movie_df['Release Date'], errors='coerce')
valid_dates = movie_df[movie_df['Release Date'].notna()]
sns.histplot(data=valid_dates, x=valid_dates['Release Date'].dt.month, bins=12, ax=ax4)
ax4.set_title('Movies by Release Month')
ax4.set_xlabel('Month')

In [ ]:
plt.tight_layout()
plt.show()

In [ ]:
# Print basic statistics
print("\nRelease Date Statistics:")
print(movie_df['Release Date'].describe())

In [ ]:
# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create subplots
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 12))

# 1. Runtime Analysis
movie_df['Runtime'] = pd.to_numeric(movie_df['Runtime'], errors='coerce')
sns.boxplot(y=movie_df['Runtime'].dropna(), ax=ax1)
ax1.set_title('Runtime Distribution')
ax1.set_ylabel('Minutes')

# 2. Year Distribution
year_counts = movie_df['year'].value_counts().sort_index()
year_counts.plot(kind='line', ax=ax2)
ax2.set_title('Movies Released by Year')
ax2.set_xlabel('Year')
ax2.set_ylabel('Number of Movies')

# 3. Genre Analysis
genre_counts = movie_df['Genres'].value_counts().head(10)
genre_counts.plot(kind='barh', ax=ax3)
ax3.set_title('Top 10 Movie Genres')

# 4. Title Length Analysis
movie_df['title_length'] = movie_df['Title'].str.len()
sns.histplot(data=movie_df, x='title_length', bins=30, ax=ax4)
ax4.set_title('Distribution of Title Lengths')
ax4.set_xlabel('Number of Characters')

plt.tight_layout()
plt.show()

# Print summary statistics
print("\nSummary Statistics:")
print("\nRuntime Statistics:")
print(movie_df['Runtime'].describe())
print("\nMost Common Genres:")
print(genre_counts.head())

In [ ]:
# Create subplots with adjusted figure size and fewer categories
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 12))

# 1. Runtime vs Year Trend (with density to handle overlapping points)
sns.kdeplot(data=movie_df, x='year', y='Runtime', ax=ax1)
ax1.set_title('Runtime Density by Year')
ax1.set_xlabel('Year')
ax1.set_ylabel('Runtime (minutes)')

# 2. Monthly Release Pattern
monthly_releases = movie_df['month'].value_counts().sort_index()
monthly_releases.plot(kind='bar', ax=ax2)
ax2.set_title('Movies Released by Month')
ax2.set_xlabel('Month')
ax2.set_ylabel('Number of Movies')

# 3. Top 5 Genres Over Time
top_5_genres = movie_df['Genres'].value_counts().head().index
genre_decade = pd.crosstab(movie_df['decade'], 
                          movie_df['Genres'])[top_5_genres]
genre_decade.plot(kind='bar', ax=ax3)
ax3.set_title('Top 5 Genres by Decade')
ax3.tick_params(axis='x', rotation=45)

# 4. Runtime Box Plot for Top 5 Genres
sns.boxplot(data=genre_runtime, x='Genres', y='Runtime', ax=ax4)
ax4.set_title('Runtime Distribution by Top Genres')
ax4.tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Print summary statistics for top genres
print("\nTop 5 Genres Statistics:")
for genre in top_5_genres:
    print(f"\n{genre}:")
    print(movie_df[movie_df['Genres'] == genre]['Runtime'].describe())